[tools]
selene = "Kampfkarren/selene@0.30.0"
stylua = "JohnnyMorganz/stylua@2.3.1"
luau-lsp = "JohnnyMorganz/luau-lsp@1.62.0"
run-in-roblox = "rojo-rbx/run-in-roblox@0.3.0"
lune = "lune-org/lune@0.10.4"
